FROM debian:buster

RUN apt update -y && apt install -y python git wget
RUN git clone https://github.com/clhunsen/cppstats.git
RUN apt install -y astyle xsltproc libxml2 libxml2-dev gcc python-dev libxml2-dev libxslt-dev zlib1g-dev python-pip
RUN wget http://131.123.42.38/lmcrs/v1.0.0/srcml_1.0.0-1_ubuntu19.04.deb && apt install -y ./srcml_1.0.0-1_ubuntu19.04.deb
RUN cd cppstats && python setup.py install
RUN mkdir repos && touch cppstats_input.txt

ENTRYPOINT ["/usr/local/bin/cppstats"]
